apiVersion: v1
name: drone-vault-secrets
description: A Vault Secrets extension for Drone
# type: application
version: 0.1.0
appVersion: 1.0.0
kubeVersion: "^1.13.0-0"
home: https://github.com/drone/drone-vault
icon: https://drone.io/apple-touch-icon.png
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/drone/drone-vault
  - https://github.com/drone/helm
maintainers:
  - name: Drone
    email: hello@drone.io
